### ISSUE TITLE
void

### ISSUE THREAD

**Issue by ghost** [revolution0x/society0x-landing#1]

**Comment by JayWelsh** [comment]
Thanks @lazaridiscom , I have added the web address to the repo.

The current rationale behind naming this "society0x-landing" is that this is the "landing site content" for society0x, but not the actual society0x "platform" itself (which resides on https://dao.society0x.org, under the [society0x repo](https://github.com/revolution0x/society0x)). I contemplated naming this "society0x-site" initially, but considering that the platform on https://dao.society0x.org is a website too made me question whether this might not be more misleading.

What do you think?

I will update the README, thank you for your assistance. 🥇

**Comment by lazaridiscom** [comment]
Please, no discussions. This will simply exhaust me, before I can dive-in.

Just rename it, nothing will explode.

**Comment by lazaridiscom** [comment]
(your stuff is currently misleading. I will NOT understand your way of understanding, but instead transform your stuff into "standard", thus visitors can grasp it much faster)
